# payload_level is an int : 
# 0 Emergency	emerg (panic)	Système inutilisable.
# 1 Alert	alert Une intervention immédiate est nécessaire.
# 2 Critical	crit  Erreur critique pour le système.
# 3 Error	err (error)  Erreur de fonctionnement.
# 4 Warning	warn (warning)	    Avertissement (une erreur peut intervenir si aucune action n'est prise).
# 5 Notice	notice		    Événement normal méritant d'être signalé.
# 6 Informational	info		    Pour information.
# 7 Debugging	debug		    Message de mise au point.

# watcher_type should be "event" or "loop"
# loop sert a lire toutes les "loop_sleep" le contenu du repertoire  et supprime les fichiers selon le removetime
# event supprime les fichiers dès leur creation
# si graylog.ip est défini une trace est envoyé au serveur à chaque suppression

title = "TOML fred service config file"

[owner]
name = "fredix"
organization = ""
dob = 2017-09-10T20:30:00Z


[graylog]
  ip = "" #set empty to not use graylog
  format = "gelf"
  protocol = "udp"
  port = 12666



[watchers]
  [watchers.test1]
  watcher_type = "loop"
  name = "Watch *.tmp in test"
  directory = "/tmp/test"
  ext_file = ".tmp" # "*" to match all files
  # define file_size : =size or <size or >size
  file_size = "=0"
  size_unit = "bytes" # bytes , kilobytes, megabytes , gigabytes , terabytes
  recursive = true # set false to not remove directories, otherwise all directories and their contents will be erased
  payload_host = "srvprod1"
  payload_level = 6
  environment = "prod"
  # écart entre la date du fichier et du systeme, avant suppression
  # format : Nh Nm Ns (240h for 10 days)  
  removetime = "1h"
  # scan le répertoire toutes les , format : Nh Nm Ns
  loop_sleep = "5m"


 [watchers.test2]
  watcher_type = "event"
  name = "Watcher *.log in test2"
  directory = "/tmp/test2"
  ext_file = ".log"
  # define file_size : =size or <size or >size
  file_size = "=0"
  size_unit = "bytes" # bytes , kilobytes, megabytes , gigabytes , terabytes
  recursive = false
  payload_host = "srvlog1"
  payload_level = 6
  environment = "prod"